"""Add user column

Revision ID: 74fc2c59fa4e
Revises: 2860a03c61f2
Create Date: 2019-11-25 10:28:43.471438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fc2c59fa4e'
down_revision = '2860a03c61f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'user')
    # ### end Alembic commands ###
